### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by kimymt** [imksoo/nostr-global-viewer#9]
Cloud you please add belows to Live Example?

[srtrelay.c-stellar.net/](https://srtrelay.c-stellar.net/)

[view-relay.mymt.casa/](https://view-relay.mymt.casa/)

**Comment by imksoo** [comment]
プルリクにしてもらえます？

**Comment by kimymt** [comment]
やってみます～

**Comment by imksoo** [comment]
#10 でマージしたのでクローズします。
